using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using System.Threading.Tasks;
using Formulador.Data.Repositorios;

namespace Formulador.Dominio
{
    public class Articulo
    {
        public string ARTICULO { get; set; }
        public string PLANTILLA_SERIE { get; set; }
        public string DESCRIPCION { get; set; }
        public string CLASIFICACION_1 { get; set; }
        public string CLASIFICACION_2 { get; set; }
        public string CLASIFICACION_3 { get; set; }
        public float FACTOR_CONVER_1 { get; set; }
        public float FACTOR_CONVER_2 { get; set; }
        public float FACTOR_CONVER_3 { get; set; }
        public string TIPO { get; set; }
        public string ORIGEN_CORP { get; set; }
        public float PESO_NETO { get; set; }
        public float PESO_BRUTO { get; set; }
        public float VOLUMEN { get; set; }
        public int BULTOS { get; set; }
        public string ARTICULO_CUENTA { get; set; }
        public string IMPUESTO { get; set; }
        public string UNIDAD_ALMACEN { get; set; }
        public string UNIDAD_EMPAQUE { get; set; }
        public string UNIDAD_VENTA { get; set; }
        public float FACTOR_EMPAQUE { get; set; }
        public float FACTOR_VENTA { get; set; }
        public float EXISTENCIA_MINIMA { get; set; }
        public float EXISTENCIA_MAXIMA { get; set; }
        public float PUNTO_DE_REORDEN { get; set; }
        public string COSTO_FISCAL { get; set; }
        public string COSTO_COMPARATIVO { get; set; }
        public float COSTO_PROM_LOC { get; set; }
        public float COSTO_PROM_DOL { get; set; }
        public float COSTO_STD_LOC { get; set; }
        public float COSTO_STD_DOL { get; set; }
        public float COSTO_ULT_LOC { get; set; }
        public float COSTO_ULT_DOL { get; set; }
        public float PRECIO_BASE_LOCAL { get; set; }
        public float PRECIO_BASE_DOLAR { get; set; }
        public DateTime ULTIMA_SALIDA { get; set; }
        public DateTime ULTIMO_MOVIMIENTO { get; set; }
        public DateTime ULTIMO_INGRESO { get; set; }
        public DateTime ULTIMO_INVENTARIO { get; set; }
        public string CLASE_ABC { get; set; }
        public int FRECUENCIA_CONTEO { get; set; }
        public string CODIGO_BARRAS_VENT { get; set; }
        public string CODIGO_BARRAS_INVT { get; set; }
        public string ACTIVO { get; set; }
        public string USA_LOTES { get; set; }
        public string OBLIGA_CUARENTENA { get; set; }
        public int MIN_VIDA_COMPRA { get; set; }
        public int MIN_VIDA_CONSUMO { get; set; }
        public int MIN_VIDA_VENTA { get; set; }
        public int VIDA_UTIL_PROM { get; set; }
        public int DIAS_CUARENTENA { get; set; }
        public string PROVEEDOR { get; set; }
        public string ARTICULO_DEL_PROV { get; set; }
        public float ORDEN_MINIMA { get; set; }
        public int PLAZO_REABAST { get; set; }
        public float LOTE_MULTIPLO { get; set; }
        public string NOTAS { get; set; }
        public string UTILIZADO_MANUFACT { get; set; }
        public string USUARIO_CREACION { get; set; }
        public DateTime FCH_HORA_CREACION { get; set; }
        public string USUARIO_ULT_MODIF { get; set; }
        public DateTime FCH_HORA_ULT_MODIF { get; set; }
        public string USA_NUMEROS_SERIE { get; set; }
        public string MODALIDAD_INV_FIS { get; set; }
        public string FEMA { get; set; }
        public string ORIGINAL { get; set; }
        public string TIPO_ENVASE { get; set; }
        public string PRESENTACION { get; set; }
        public string ADMINISTRATIVO { get; set; }
        public float COSTO_REPO_LOC { get; set; }
        public float COSTO_REPO_DOL { get; set; }
        public string REVENTA { get; set; }
        public string ALERGENICO { get; set; }
        public float PORC_COMISION { get; set; }
        public string TIPO_COMISION { get; set; }
        public float PORC_ERROR_ESTIM_VTA { get; set; }
        public float PORC_BONIF_NUEVA_VTA { get; set; }
        public int MESES_ANT_NUEVA_VTA { get; set; }
        public int MESES_BONIF_NUEVA_VTA { get; set; }
        public string SITUACION { get; set; }
        public DateTime FECHA_COSTO_REPO { get; set; }
        public int flg_dbf { get; set; }
        public string TIPO_PRECIO { get; set; }
        public string PRESENTACION_ORIGINAL { get; set; }
        public string SUBFIJO_COSTO { get; set; }
        public string grupo { get; set; }
        public string UNIDAD_CONTABLE { get; set; }
        public float FACTOR_CONTABLE { get; set; }
        public string FLAG_CONTABLE { get; set; }
        public string FLAG_EXONERA { get; set; }
        public string FLAG_AGRUPA { get; set; }
        public string ARTICULO_CUENTA_DETALLE { get; set; }
        public string UNIDAD_ESTIND { get; set; }
        public float FACTOR_ESTIND { get; set; }
        public int FLG_FACTOR_FIJO { get; set; }
        public string OBS_ESTIND { get; set; }
        public string FLG_COSTEO { get; set; }
        public string CAMARA { get; set; }
        public float ref_costo_soles { get; set; }
        public float ref_costo_dolar { get; set; }
        public string periodo_costo_prom { get; set; }
        public string ARTICULO_CUENTA_OLD { get; set; }
        public string ARTICULO_CUENTA_NEW { get; set; }
        public string TIPO_COD_BARRA_DET { get; set; }
        public string TIPO_COD_BARRA_ALM { get; set; }
        public string USA_REGLAS_LOCALES { get; set; }
        public string CLASIFICACION_4 { get; set; }
        public string CLASIFICACION_5 { get; set; }
        public string CLASIFICACION_6 { get; set; }
        public float FACTOR_CONVER_4 { get; set; }
        public float FACTOR_CONVER_5 { get; set; }
        public float FACTOR_CONVER_6 { get; set; }
        public string PERECEDERO { get; set; }
        public string GTIN { get; set; }
        public string MANUFACTURADOR { get; set; }
        public int NoteExistsFlag { get; set; }
        public DateTime RecordDate { get; set; }
        public Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime CreateDate { get; set; }
        public string DESCRIPCION_GENERICA { get; set; }
        public string FORMULA { get; set; }
        public string COD_UNIDAD { get; set; }
        public float FACTOR_ING_NATUR { get; set; }
        public int DIAS_INV { get; set; }
        public string OBSERVADO { get; set; }
        public string PROHIBIDO { get; set; }
        public DateTime FECHA_OBPR { get; set; }
        public string TERCEROS { get; set; }
        public string CA { get; set; }
        public string TIPO_PERCEPCION { get; set; }
        public string NUMERAL_PERCEPCION { get; set; }
        public string INVENTARIABLE { get; set; }
        public string CODIGO_RETENCION { get; set; }
        public string RETENCION_VENTA { get; set; }
        public string RETENCION_COMPRA { get; set; }
        public string MODELO_RETENCION { get; set; }
        public string ESTILO { get; set; }
        public string TALLA { get; set; }
        public string COLOR { get; set; }
        public string TIPO_COSTO { get; set; }
        public string ARTICULO_ENVASE { get; set; }
        public string ES_ENVASE { get; set; }
        public string USA_CONTROL_ENVASE { get; set; }
        public float COSTO_PROM_COMPARATIVO_LOC { get; set; }
        public float COSTO_PROM_COMPARATIVO_DOLAR { get; set; }
        public float COSTO_PROM_ULTIMO_LOC { get; set; }
        public float COSTO_PROM_ULTIMO_DOL { get; set; }
        public string UTILIZADO_EN_CONTRATOS { get; set; }
        public string VALIDA_CANT_FASE_PY { get; set; }
        public string OBLIGA_INCLUIR_FASE_PY { get; set; }
        public string ART_GENERICO { get; set; }
        public string U_CODIGO_CATALOGO { get; set; }
        public string U_CODIGO_DETRACCION { get; set; }
    }
}
